# Generated by Django 4.1.2 on 2022-12-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='patientCI',
            field=models.CharField(max_length=11),
        ),
    ]
