# Generated by Django 4.1.2 on 2022-12-03 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_test_patientci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='patientCI',
        ),
        migrations.AddField(
            model_name='systemevent',
            name='type',
            field=models.CharField(default='NOTICE', max_length=32),
        ),
        migrations.AddField(
            model_name='test',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.patient'),
        ),
    ]
