# Generated by Django 4.1.2 on 2022-12-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_test_patientci_systemevent_type_test_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='iconpath',
            field=models.CharField(default='img/icons/user.png', max_length=128),
        ),
    ]
