# Generated by Django 4.1.2 on 2022-12-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_systemuser_iconpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='iconpath',
        ),
        migrations.AddField(
            model_name='systemuser',
            name='icon_path',
            field=models.CharField(default='img/profiles/default_profile.png', max_length=128),
        ),
    ]
