# Generated by Django 4.1.2 on 2022-12-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_systemuser_iconpath_systemuser_icon_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='sex',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
