# Generated by Django 4.1.2 on 2022-12-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_systemuser_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='icon_path',
            field=models.CharField(default='default_profile.png', max_length=128),
        ),
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
