# Generated by Django 4.1.2 on 2022-12-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_systemuser_icon_path_alter_worker_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='state',
            field=models.CharField(default='waiting', max_length=32),
        ),
    ]
