# Generated by Django 4.1.2 on 2022-12-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_test_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='patient',
        ),
        migrations.AddField(
            model_name='test',
            name='patientCI',
            field=models.CharField(default='00000000000', max_length=11),
        ),
        migrations.AddField(
            model_name='test',
            name='type',
            field=models.CharField(default='uncategorized', max_length=32),
        ),
        migrations.AlterField(
            model_name='test',
            name='result',
            field=models.CharField(default='', max_length=256),
        ),
    ]
