# Generated by Django 4.1.2 on 2022-12-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_test_patient_test_patientci_test_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blod_group',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='systemevent',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='systemevent',
            name='message',
            field=models.CharField(default='event', max_length=512),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='begin_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='resolution_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='result',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='testID',
            field=models.CharField(default='0000', max_length=11),
        ),
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(default='worker', max_length=50),
        ),
    ]
