# Generated by Django 4.1.2 on 2022-12-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_patient_blod_group_alter_systemevent_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blod_group',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='ci',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='sex',
            field=models.CharField(default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='test',
            name='patientCI',
            field=models.CharField(default='00000000000', max_length=12),
        ),
        migrations.AlterField(
            model_name='test',
            name='testID',
            field=models.CharField(default='0000', max_length=12),
        ),
    ]
