# Generated by Django 4.1.2 on 2022-12-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_patient_blod_group_alter_systemuser_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='system_role',
            field=models.CharField(default='patient', max_length=128),
        ),
    ]
