# Generated by Django 4.1.2 on 2022-12-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_worker_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemevent',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
