# Generated by Django 4.1.2 on 2022-12-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_systemevent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemevent',
            name='title',
            field=models.CharField(default='title', max_length=120),
        ),
        migrations.AlterField(
            model_name='systemevent',
            name='type',
            field=models.CharField(default='normal', max_length=32),
        ),
    ]
