# Generated by Django 4.1.2 on 2022-12-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_systemevent_title_alter_systemevent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='ci',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='testID',
            field=models.CharField(default='0000', max_length=12, unique=True),
        ),
    ]
